config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  #URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  # config/routes.rb
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  # ジャンル検索
  get 'public/genres/:id/search' => 'public/searches#search_genre'

  # 会員側のルーティング設定
  scope module: :public do
    # トップページ
    root to: "homes#top"
    # アバウトページ
    get "home/about"=>"homes#about"
    # 商品検索
    get "search" => "searches#search"
    # 商品
    resources :items, only: [:index, :show]
    # 顧客
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    # カート内
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    # 注文情報
    resources :orders, only: [:new, :index, :create, :show]
    post 'confirm' => 'orders#confirm', as: 'confirm'
    get 'thanks' => 'orders#thanks', as: 'thanks'
    get 'confirm', to: 'orders#error', as: 'error'
    # 配送先
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  # 管理者側のルーティング設定
  namespace :admin do

    # トップページ(商品一覧画面)
    root to: "homes#top"
    #検索
    get "search" => "searches#search"
    # 商品
    resources :items, only: [:new, :index, :create, :show, :edit, :update]
    # ジャンル
    resources :genres, only: [:index, :create, :edit, :update]
    # 顧客
    resources :customers, only: [:index, :show, :edit, :update]
    # 注文詳細画面(ステータス編集を兼ねる)/注文ステータスの更新
    resources :orders, only: [:show, :index, :update] do
      # 製作ステータスの更新
    resources :order_details, only: [:update]
      end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def customer_status
    if is_active == true
      "有効"
    else
      "退会"
    end
  end

  def full_name
    last_name + ' ' + first_name
  end

  def full_name_kana
    last_name_kana + ' ' + first_name_kana
  end

  def self.search_for(content)

    @customer = Customer.where(['first_name LIKE ? OR last_name LIKE ? ', "%#{content}%", "%#{content}%"])
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index 
    @customers = Customer.page(params[:page]).per(10)
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end
  
  def search
    @search_term = params[:search_term]
    @customers = Customer.where("name LIKE ?", "%#{@search_term}%")
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name,
    :first_name,
    :last_name_kana,
    :first_name_kana,
    :phone_number,
    :postal_code,
    :address,
    :email,
    :is_active
    )
  end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_index.html.erb
<table class="table border-top border-bottom mt-4" style="background-color: #fffaf0;">
  <thead class="bg-light">
    <tr>
      <th style="background-color: #ccc8c0; width: 20%;">会員ID</th>
      <th style="background-color: #ccc8c0; width: 20%;">氏名</th>
      <th style="background-color: #ccc8c0; width: 20%;">メールアドレス</th>
      <th style="background-color: #ccc8c0; width: 20%;">ステータス</th>
    </tr>
  </thead>
  <tbody style="background-color: #fffaf0;">
  <% customers.each do |customer| %>
    <tr>
      <td class="align-middle"><%= customer.id %></td>
      <td class="align-middle">
        <%= link_to admin_customer_path(customer), :style => "color: #A07B35;"  do %>
          <%= customer.full_name %>
        <% end %>
      </td>
      <td class="align-middle"><%= customer.email %></td>
      <th class="align-middle">
        <% if customer.is_active %>
          <span class="text-success">有効</span>
        <% else %>
          <span class="text-danger">退会</span>
        <% end %>
      </th>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/customers/edit.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col mt-3">
      <h3  class="mb-4" style="font-weight:bold; color:#A07B35; font-family: serif; font-size:30px;">Edit Member Information for Mr.<strong><%= @customer.full_name %></strong> </h3>
      <%= form_with model: @customer, url: admin_customer_path(@customer) do |f| %>
      <table class = "table table-borderless", style="background-color: #fffaf0;">
        <tr>
          <th class="align-middle">会員ID</th>
          <td class="align-middle"><%= @customer.id %></td>
        </tr>
        <tr>
          <th class="align-middle">氏名</th>
          <td class="align-middle"><%= f.text_field :last_name %>  　　<%= f.text_field :first_name %></td>
        </tr>
        <tr>
          <th class="align-middle">フリガナ</th>
          <td class="align-middle"><%= f.text_field :last_name_kana %>  　　<%= f.text_field :first_name_kana %></td>
        </tr>
        <tr>
          <th class="align-middle">郵便番号</th>
          <td class="align-middle"><%= f.text_field :postal_code %></td>
        </tr>
        <tr>
          <th class="align-middle">住所</th>
          <td class="align-middle" colspan="2"><%= f.text_field :address, style: "width: 500px;" %></td>
        </tr>
        <tr>
          <th class="align-middle">電話番号</th>
          <td class="align-middle"><%= f.text_field :phone_number %></td>
        </tr>
        <tr>
          <th class="align-middle">メールアドレス</th>
          <td class="align-middle"><%= f.text_field :email %></td>
        </tr>
        <tr>
          <th class="align-middle">会員ステータス</th>
          <td class="align-middle">
            <span><%= f.radio_button :is_active, "true" %>有効</span>
            <span class="pl-3"><%= f.radio_button :is_active, "false" %>退会</span>
          </td>
        </tr>
        <tr>
          <td></td>
          <td class="pt-5">
            <%= f.submit "変更を保存", class: "btn btn-lg btn-success", style:"width: 150px" %>
          </td>
        </tr>
      </table>
        <% end %>
    </div>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-10">
      <div class="row">
        <div class="col-lg-8">
          <h2 class="mb-4" style="font-weight:bold; color:#A07B35; font-family:'Times New Roman'; font-size:45px;"><strong>Customers</strong></h2>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <%= render "admin/customers/index", customers: @customers %>
         </div>
      </div>
    </div>
  </div>
  <div class = "row justify-content-center" >
    <%= paginate @customers, theme: 'twitter-bootstrap-4' %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col mt-3">
      <h3 class="mb-4" style="font-weight:bold; color:#A07B35; font-family: serif;; font-size:30px; ">Product Details for Mr.<strong><%= @customer.full_name %></strong></h3>
      <table class = "table table-borderless", style="background-color: #fffaf0;">
        <tr>
          <th style="background-color: #ccc8c0; width: 20%;">会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th style="background-color: #ccc8c0; width: 20%;">氏名</th>
          <td><%= @customer.full_name %></td>
        </tr>
        <tr>
          <th style="background-color: #ccc8c0; width: 20%;">フリガナ</th>
          <td><%= @customer.full_name_kana %></td>
        </tr>
        <tr>
          <th style="background-color: #ccc8c0; width: 20%;">郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th style="background-color: #ccc8c0; width: 20%;">住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th style="background-color: #ccc8c0; width: 20%;">電話番号</th>
          <td><%= @customer.phone_number %></td>
        </tr>
        <tr>
          <th style="background-color: #ccc8c0; width: 20%;">メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th style="background-color: #ccc8c0; width: 20%;">会員ステータス</th>
          <th>
            <% if @customer.is_active %>
              <span class="text-success">有効</span>
            <% else %>
              <span class="text-danger">退会</span>
            <% end %>
           </th>
        </tr>
        <tr>
          <th style= "width: 20%;"></th>
          <td>
            <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %>
            <%= link_to "注文履歴一覧を見る", admin_root_path, class: "btn btn-info ml-5" %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>