config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  #URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  # config/routes.rb
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  # ジャンル検索
  get 'public/genres/:id/search' => 'public/searches#search_genre'

  # 会員側のルーティング設定
  scope module: :public do
    # トップページ
    root to: "homes#top"
    # アバウトページ
    get "home/about"=>"homes#about"
    # 商品検索
    get "search" => "searches#search"
    # 商品
    resources :items, only: [:index, :show]
    # 顧客
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    # カート内
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    # 注文情報
    resources :orders, only: [:new, :index, :create, :show]
    post 'confirm' => 'orders#confirm', as: 'confirm'
    get 'thanks' => 'orders#thanks', as: 'thanks'
    get 'confirm', to: 'orders#error', as: 'error'
    # 配送先
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  # 管理者側のルーティング設定
  namespace :admin do

    # トップページ(商品一覧画面)
    root to: "homes#top"
    #検索
    get "search" => "searches#search"
    # 商品
    resources :items, only: [:new, :index, :create, :show, :edit, :update]
    # ジャンル
    resources :genres, only: [:index, :create, :edit, :update]
    # 顧客
    resources :customers, only: [:index, :show, :edit, :update]
    # 注文詳細画面(ステータス編集を兼ねる)/注文ステータスの更新
    resources :orders, only: [:show, :index, :update] do
      # 製作ステータスの更新
    resources :order_details, only: [:update]
      end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items, dependent: :destroy
     
   validates :name, presence: true, uniqueness: true, length: {in: 2..20}

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
def index
  @genre = Genre.new
  @genres = Genre.all
end

def create
  @genre = Genre.new(genre_params)
  @genre.save
  flash[:notice] = "新規作成に成功しました。"
  @genres = Genre.all
end

def edit
  @genre = Genre.find(params[:id])
end

def update
  @genre=Genre.find(params[:id])
  @genre.update(genre_params)
  redirect_to admin_genres_path
end

private

def genre_params
  params.require(:genre).permit(:name)
end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_form.html.erb
<%= form_with model: genre, url: admin_genres_path, method: :post, local: false do |f| %>
  <div class="form-row align-items-center mt-4">
    <div class="col-md-3 mb-2">
      <%= f.label :name, "ジャンル名", class: "text-md-right", style: "font-size: 22px; font-weight:bold; " %>
    </div>
    <div class="col-md-6 mb-2">
      <%= f.text_field :name, placeholder: 'ジャンル名', class: "form-control" %>
    </div>
    <div class="col-md-3 mb-2 pl-5">
      <%= f.submit "新規登録", class: "btn btn-success btn-sm" , style: "width: 170px; height: 40px; border-radius: 12px;" %>
    </div>
  </div>
<% end %>

app/views/admin/genres/_index.html.erb
<table class="table border-top border-bottom table-condensed mt-4" style="background-color: #fffaf0;">
  <thead class="thead-center">
    <tr>
      <th class="text-center" style="background-color: #ccc8c0; padding-right: 50px;">ジャンル</th>
      <th class="text-center" style="background-color: #ccc8c0; "></th>
    </tr>
  </thead>
  <tbody>
    <% genres.each do |genre| %>
      <tr>
        <td class="text-center align-middle" style="padding-right: 50px; color:#A07B35; font-family: serif;"><%= genre.name %></td>
        <td class="text-center align-middle" style="color:#A07B35; font-family: serif;">
          <%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success btn-sm", style: "width: 120px; height: 40px; border-radius: 12px; line-height:30px;" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/genres/create.js.erb
$('#genre_name').val("");
$('#genre_index').html("<%= j(render 'admin/genres/index', genres: @genres) %>");

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 mx-auto">
      <h2 class="mb-4" style="font-weight:bold; color:#A07B35; font-family:serif; font-size:45px; text-align: center;"><strong>Category Edit</strong></h2>

      <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
        <div class="form-row align-items-center">
          <div class="col-md-3 mb-1 text-md-right mx-auto">
            <%= f.label :name, "ジャンル名" %>
          </div>
          <div class="col-md-5 mb-1 mx-auto">
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="col-md-2 mb-2 mx-auto">
            <%= f.submit "変更を保存", class: "btn btn-success btn-block", style: "border-radius: 12px;" %>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 mx-auto">
      <h2 class="mt-5" style="font-weight:bold; color:#A07B35; font-family:serif; font-size:45px; "><strong>Category List&Addition</strong></h2>
        <%= render 'admin/genres/form', genre: @genre %>
      <div id='genre_index'>
        <%= render 'admin/genres/index', genres: @genres %>
      </div>
    </div>
  </div>
</div>