config/routes.rb
Rails.application.routes.draw do

  # 顧客用
  #URL /customers/sign_in ...
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  # config/routes.rb
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: 'admin/sessions'
  }

  # ジャンル検索
  get 'public/genres/:id/search' => 'public/searches#search_genre'

  # 会員側のルーティング設定
  scope module: :public do
    # トップページ
    root to: "homes#top"
    # アバウトページ
    get "home/about"=>"homes#about"
    # 商品検索
    get "search" => "searches#search"
    # 商品
    resources :items, only: [:index, :show]
    # 顧客
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    # カート内
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]
    # 注文情報
    resources :orders, only: [:new, :index, :create, :show]
    post 'confirm' => 'orders#confirm', as: 'confirm'
    get 'thanks' => 'orders#thanks', as: 'thanks'
    get 'confirm', to: 'orders#error', as: 'error'
    # 配送先
    resources :addresses, only: [:index, :edit, :create, :update, :destroy]
  end

  # 管理者側のルーティング設定
  namespace :admin do

    # トップページ(商品一覧画面)
    root to: "homes#top"
    #検索
    get "search" => "searches#search"
    # 商品
    resources :items, only: [:new, :index, :create, :show, :edit, :update]
    # ジャンル
    resources :genres, only: [:index, :create, :edit, :update]
    # 顧客
    resources :customers, only: [:index, :show, :edit, :update]
    # 注文詳細画面(ステータス編集を兼ねる)/注文ステータスの更新
    resources :orders, only: [:show, :index, :update] do
      # 製作ステータスの更新
    resources :order_details, only: [:update]
      end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

    validates :postal_code, presence: true
    validates :address, presence: true
    validates :name, presence: true

    # options_from_collection_for_select に直接「郵便番号 住所 宛名」を書けない
    # ので、これらを表示するためのメソッドをモデルに記入する
    def address_display
      '〒' + postal_code + ' ' + address + ' ' + name
    end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.with_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true

  def customer_status
    if is_active == true
      "有効"
    else
      "退会"
    end
  end

  def full_name
    last_name + ' ' + first_name
  end

  def full_name_kana
    last_name_kana + ' ' + first_name_kana
  end

  def self.search_for(content)

    @customer = Customer.where(['first_name LIKE ? OR last_name LIKE ? ', "%#{content}%", "%#{content}%"])
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
   has_many :items, dependent: :destroy
     
   validates :name, presence: true, uniqueness: true, length: {in: 2..20}

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :order_details

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :genre_id, presence: true
  validates :image, presence: true

  def get_image(width, height)
    if image.attached?
      image.variant(resize_to_fill: [width, height]).processed
    end
  end

  def with_tax_price
    (price * 1.1).floor
  end

  def subtotal
    item.with_tax_price * amount
  end

  # 検索方法分岐
  def self.looks(search, word)
    if search == "partial"
      @item = Item.where("name LIKE?","%#{word}%")
    end
  end

  def self.search_for(content)
    @item = Item.where("name LIKE ?", "%#{content}%")
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  belongs_to :customer

  # enum の定義
  enum payment_method: { credit_card: 0, transfer: 1 }

  # 注文ステータス
  enum status: {
    awaiting_payment: 0,
    payment_confirmed: 1,
    making: 2,
    shipping_in_process: 3,
    shipped: 4
  }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  # 制作ステータス => 0:製作不可 1:製作待ち 2:製作中 3:製作完了
  enum making_status: {
    unable_making: 0,
    waiting_making: 1,
    in_making: 2,
    making_completed: 3
  }

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  before_action :authenticate_admin!

  def top
    @orders = Order.page(params[:page]).per(10)
  end

  private

  def order_params
    params.require(:order).permit(:status)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    # @items = Item.all
    # ページネーションを使いたい場合は Kaminari や will_paginate などの gem をインストールする必要があります
  # 例: Kaminari を使用する場合
  # Kaminari を使用してページネーションする
    @items = Item.page(params[:page]).per(10)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def show
    @items = Item.all
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
     @item = Item.find(params[:id])

    if @item.update(item_params)

      redirect_to admin_items_path(@item.id)
    else
      redirect_to edit_admin_item_path(@item.id)
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :genre_id, :is_active, :image) #( :body )をpermit内へ追加
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/seaches_helper.rb
module Admin::SeachesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<!--管理者側の、サインインの機能-->
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header.html.erb
<header style="position: fixed; top: 0; width: 100%; background: #0A6651; height: 100px; z-index: 1000;">
  <nav class= "navbar navbar-expand-lg navbar-dark" style="background: #0A6651; height:100px;">
    <div class="container">
      <a class="navbar-brand" href="/" style="font-family:'Times New Roman'; font-size:40px;"><span>NaganoCake</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto" style="margin-top: 22px;">
          <% if admin_signed_in? %>
            <li>
              <%= link_to admin_items_path, class: "btn btn-outline-light rounded-pill mr-2", :style => "font-family:'Times New Roman'; font-size:20px;"  do %>
              <i class="fa-solid fa-cake-candles mr-2"></i>Items
              <% end %>
            </li>
            <li>
              <%= link_to admin_customers_path, class: "btn btn-outline-light rounded-pill mr-2", :style => "font-family:'Times New Roman'; font-size:20px;"  do %>
              <i class="fa-solid fa-users mr-2"></i>Customers
              <% end %>
            </li>
            <li>
              <%= link_to admin_root_path, class: "btn btn-outline-light rounded-pill mr-2", :style => "font-family:'Times New Roman'; font-size:20px;"  do %>
              <i class="fa-solid fa-cart-shopping mr-2"></i>Orders
              <% end %>
            </li>
            <li>
              <%= link_to admin_genres_path, class: "btn btn-outline-light rounded-pill mr-2", :style => "font-family:'Times New Roman'; font-size:20px;"  do %>
              <i class="fa-solid fa-list mr-2"></i>Category
              <% end %>
            </li>
            <li>
              <%= link_to destroy_admin_session_path, method: :delete, class: "btn btn-outline-light rounded-pill mr-2", :style => "font-family:'Times New Roman'; font-size:20px;"  do %>
              <i class="fa-solid fa-right-from-bracket mr-2"></i>Log out
              <% end %>
            </li>
            <div>
              <%= render "admin/searches/form" %>
            </div>
          <% else %>
            <li>
              <%= link_to home_about_path, class: "btn btn-outline-light rounded-pill mr-2", :style => "font-family:'Times New Roman'; font-size:20px; margin-bottom: 20px;"  do %>
              <i class="fa-solid fa-hand-holding-heart mr-2"></i> About
              <% end %>
            </li>
            <li>
              <%= link_to items_path, class: "btn btn-outline-light rounded-pill mr-2", :style => "font-family:'Times New Roman'; font-size:20px; margin-bottom: 20px;"  do %>
              <i class="fa-solid fa-cake-candles mr-2"></i> Items
              <% end %>
            </li>
            <li>
              <%= link_to new_customer_registration_path, class: "btn btn-outline-light rounded-pill mr-2", :style => "font-family:'Times New Roman'; font-size:20px; margin-bottom: 20px;"  do %>
              <i class="fa-solid fa-user-plus mr-1"></i> Sign Up
              <% end %>
            </li>
            <li>
              <%= link_to new_customer_session_path, class: "btn btn-outline-light rounded-pill mr-2", :style => "font-family:'Times New Roman'; font-size:20px; margin-bottom: 20px;"  do %>
              <i class="fa-solid fa-arrow-right-to-bracket mr-2"></i> Log In
              <% end %>
            </li>
          <% end %>
        </ul>
       </nav>
    </div>
  </div>
</header>

app/views/layouts/_public_header.html.erb
<header style="position: fixed; top: 0; width: 100%; background: #0A6651; height: 100px; z-index: 1000;">
  <nav class="navbar navbar-expand-lg navbar-dark" style="background: #0A6651; height:100px;">
    <div class="container">
      <div class="logo-section d-flex justify-content-start">
        <a class="navbar-brand" href="/" style="font-family:'Times New Roman'; font-size:40px;"><span>NaganoCake</span></a>
      </div>  
      <% if customer_signed_in? %>
        <p class = "text-white" style="font-family: 'Playfair Display', serif; color: black; margin-top: 20px;">Welcome to <%= current_customer.first_name_kana %>！</p>
      <% end %>
      <div class= "collapse navbar-collapse" id="navbarNavDropdown">
      <ul class= "navbar-nav ml-auto">
        <% if customer_signed_in? %>
          <li>
            <%= link_to my_page_path, class: "btn btn-outline-light rounded-pill mr-2 md-3", :style => "font-family:'Times New Roman'; font-size:20px;"  do%>
              <i class="fa-solid fa-user mr-2"></i>Mypage
            <% end %>
          </li>
          <li>
            <%= link_to items_path, class: "btn btn-outline-light rounded-pill mr-2", :style => "font-family:'Times New Roman'; font-size:20px;"  do %>
              <i class="fa-solid fa-cake-candles mr-2"></i>Items
            <% end %>
          </li>
          <li>
            <%= link_to cart_items_path, class: "btn btn-outline-light rounded-pill mr-2", :style => "font-family:'Times New Roman'; font-size:20px;"  do %>
              <i class="fa-solid fa-cart-shopping mr-2"></i>Carts
            <% end %>
          </li>
          <li>
            <%= link_to destroy_customer_session_path, method: :delete, class: "btn btn-outline-light rounded-pill mr-2", :style => "font-family:'Times New Roman'; font-size:20px;"  do %>
               <i class="fa-solid fa-right-from-bracket mr-2"></i>Log Out
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to home_about_path, class: "btn btn-outline-light rounded-pill mr-2", :style => "font-family:'Times New Roman'; font-size:20px;"  do %>
              <i class="fa-solid fa-hand-holding-heart mr-2"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to items_path, class: "btn btn-outline-light rounded-pill mr-2", :style => "font-family:'Times New Roman'; font-size:20px;" do %>
              <i class="fa-solid fa-cake-candles mr-2"></i> Items
            <% end %>
          </li>
          <li>
            <%= link_to new_customer_registration_path, class: "btn btn-outline-light rounded-pill mr-2", :style => "font-family:'Times New Roman'; font-size:20px;" do %>
             <i class="fa-solid fa-user-plus mr-1"></i> Sign Up
            <% end %>
          </li>
          <li>
           <%= link_to new_customer_session_path, class: "btn btn-outline-light rounded-pill mr-2", :style => "font-family:'Times New Roman'; font-size:20px;" do %>
            <i class="fa-solid fa-arrow-right-to-bracket mr-2"></i> Log In
            <% end %>
          </li>
        <% end %>
      <div style="margin-top: 3px;">
          <%= render "public/searches/search" %>
        </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <script src="https://kit.fontawesome.com/943c365873.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <style>
      body {
        background-color: #FFF9E6;
        padding-bottom: 80px; /* フッターの高さに合わせて調整してください */
        margin-bottom: 0; /* 余分なマージンを削除 */
      }

       main {
        padding-top: 120px; /* ヘッダーの高さ + 追加の余白分 */
        margin-bottom: 50px;
      }

      footer {
        background: #0A6651;
        height: 80px;
        position: fixed;
        bottom: 0;
        width: 100%;
      }

      .footer-text {
        color: white;
        line-height: 80px; /* 高さと揃えるためにフッターの高さと同じにします */
        text-align: center;
      }
    </style>
  </head>

  <body>
    
    <% if request.fullpath.include? "/admin" %>
      <%= render "layouts/admin_header" %>
    <% else %>
      <%= render "layouts/public_header" %>
    <% end %>
    <main>
      <div class= "ml-4">
        <%= flash[:notice] %>
      </div>
      <%= yield %>
    </main>
    <footer>
      <div class="fixed-bottom">
        <p class="footer-text", style="font-family:'Times New Roman'; font-size:20px;">team akaboshi</p>
      </div>
    </footer>
  </body>
</html>